echo "cloning dotfiles"
git clone git@github.com:sehyunc/dotfiles.git "${HOME}/dotfiles"
ln -s "${HOME}/dotfiles/.zshrc" "${HOME}/.zshrc"
ln -s "${HOME}/dotfiles/.gitignore_global" "${HOME}/.gitignore_global"
ln -s "${HOME}/dotfiles/.gitconfig" "${HOME}/.gitconfig"
ln -s "${HOME}/dotfiles/.my_bin" "${HOME}/.my_bin"
ln -s "${HOME}/dotfiles/.vimrc" "${HOME}/.vimrc"
ln -s "${HOME}/dotfiles/.vimrc-parts" "${HOME}/.vimrc-parts"
